ROLL			= osg
VERSION			= 3.1.22
NAME    		= roll-$(ROLL)-usersguide
RELEASE			= 0
MANUALRELEASE 		= V7_8_8

SUMMARY_COMPATIBLE	= $(VERSION)
SUMMARY_MAINTAINER	= Rocks Group
SUMMARY_ARCHITECTURE	= i386, x86_64

ROLL_REQUIRES		= base kernel os
ROLL_CONFLICTS		=

