ROLL			= osg
VERSION			= 3.3.27
NAME    		= roll-$(ROLL)-usersguide
RELEASE			= 0
MANUALRELEASE 		= V8_4_12

SUMMARY_COMPATIBLE	= $(VERSION)
SUMMARY_MAINTAINER	= Rocks Group
SUMMARY_ARCHITECTURE	= i386, x86_64

ROLL_REQUIRES		= base kernel os ganglia
ROLL_CONFLICTS		= condor java

