#!/bin/bash

TARVER=`cat version.mk | grep VERSION | cut -d\  -f 3`
TARMAJ=`cat version.mk | grep VERSION | cut -d\  -f 3 | cut -d. -f 1`
TARMIN=`cat version.mk | grep VERSION | cut -d\  -f 3 | cut -d. -f 2`
MAJVER=`lsb_release -rs | cut -d . -f 1`
FILE1=osg-client-$TARVER-1.el$MAJVER.x86_64.tar.gz
FILE2=osg-wn-client-$TARVER-1.el$MAJVER.x86_64.tar.gz

#rsync -av rsync://repo.opensciencegrid.org/osg/tarball-install/$TARVER/osg-client-$TARVER-1.el5.x86_64.tar.gz .
#rsync -av rsync://repo.opensciencegrid.org/osg/tarball-install/$TARVER/osg-client-$TARVER-1.el6.x86_64.tar.gz .
#rsync -av rsync://repo.opensciencegrid.org/osg/tarball-install/$TARVER/osg-wn-client-$TARVER-1.el5.x86_64.tar.gz .
#rsync -av rsync://repo.opensciencegrid.org/osg/tarball-install/$TARVER/osg-wn-client-$TARVER-1.el6.x86_64.tar.gz .

[ -f $FILE1 ] || wget http://repo.opensciencegrid.org/tarball-install/$TARMAJ.$TARMIN/$TARVER/$FILE1
[ -f $FILE2 ] || wget http://repo.opensciencegrid.org/tarball-install/$TARMAJ.$TARMIN/$TARVER/$FILE2
