#!/bin/bash

TARVER=3.1.22
rsync -av rsync://repo.grid.iu.edu/osg/tarball-install/$TARVER/osg-client-$TARVER-1.el5.x86_64.tar.gz .
rsync -av rsync://repo.grid.iu.edu/osg/tarball-install/$TARVER/osg-client-$TARVER-1.el6.x86_64.tar.gz .
rsync -av rsync://repo.grid.iu.edu/osg/tarball-install/$TARVER/osg-wn-client-$TARVER-1.el5.x86_64.tar.gz .
rsync -av rsync://repo.grid.iu.edu/osg/tarball-install/$TARVER/osg-wn-client-$TARVER-1.el6.x86_64.tar.gz .

